# Generated by Django 5.0.6 on 2025-10-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_host_guest_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], default='guest', max_length=10),
        ),
    ]
