
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stayfinder_web

    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped